package com.cf.dao;

import com.cf.beans.Permission;
import com.cf.beans.Role;
import com.cf.beans.User;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 13 09:19:44 EDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 13 09:19:44 EDT 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 13 09:19:44 EDT 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 13 09:19:44 EDT 2020
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 13 09:19:44 EDT 2020
     */
    int updateByPrimaryKey(User record);

    User login(Map<String, Object> map);

//    List queryUserPages(@Param("pageNum")Integer pageNum, @Param("pageSize")Integer pageSize);

    Integer queryTotalUser(Map map);

    List queryUserPages(Map map);


    int deleteGroupById(Integer[] id);

    List<Integer> queryUserRoleIdByUserId(Integer id);

    List<Role> queryAllRoles();

    int insertBatch(Map map);

    int deleteRoles(Map map);

    List<Permission> queryPermissionsByUserId(Integer id);
}